#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
import __builtin__
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.1'
__CHEETAH_versionTuple__ = (2, 4, 1, 'final', 0)
__CHEETAH_genTime__ = 1453859979.4620681
__CHEETAH_genTimestamp__ = 'Wed Jan 27 09:59:39 2016'
__CHEETAH_src__ = 'report_externel.tmpl'
__CHEETAH_srcLastModified__ = 'Tue Jan 26 18:28:22 2016'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class report_externel(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(report_externel, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''Subject: ''')
        _v = VFFSL(SL,"title",True) # u'$title' on line 1, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'$title')) # from line 1, col 10.
        write(u'''\r
MIME-Version: 1.0\r
Content-Type: text/html\r
Content-Disposition: inline\r
\r
<!doctype html>\r
<html lang="en">\r
    <head>\r
        <meta charset="UTF-8">\r
        <style type="text/css">\r
            caption {\r
                font-size:20px;\r
                font-weight:bolder;\r
            }\r
        </style>\r
    </head>\r
\r
    <body>\r
        <table border="3" align="center">\r
            <caption>\r
                ''')
        _v = VFFSL(SL,"title",True) # u'$title' on line 21, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$title')) # from line 21, col 17.
        write(u'''\r
            </caption>\r
            <tr bgcolor="CornflowerBlue" >\r
                <th>''')
        _v = VFFSL(SL,"database",True) # u'$database' on line 24, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$database')) # from line 24, col 21.
        write(u'''</th>\r
                <th>''')
        _v = VFFSL(SL,"yesterday",True) # u'$yesterday' on line 25, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$yesterday')) # from line 25, col 21.
        write(u'''</th>\r
                <th>''')
        _v = VFFSL(SL,"average",True) # u'$average' on line 26, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$average')) # from line 26, col 21.
        write(u'''</th>\r
                <th>''')
        _v = VFFSL(SL,"status",True) # u'$status' on line 27, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$status')) # from line 27, col 21.
        write(u'''</th>\r
                <th>''')
        _v = VFFSL(SL,"explain",True) # u'$explain' on line 28, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$explain')) # from line 28, col 21.
        write(u'''</th>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"cig_dw_ods_bitauto_website_d_pc",True) # u'$cig_dw_ods_bitauto_website_d_pc' on line 31, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$cig_dw_ods_bitauto_website_d_pc')) # from line 31, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"cig_dw_ods_bitauto_website_d_pc_yesterday",True) # u'$cig_dw_ods_bitauto_website_d_pc_yesterday' on line 32, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$cig_dw_ods_bitauto_website_d_pc_yesterday')) # from line 32, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"cig_dw_ods_bitauto_website_d_pc_average",True) # u'$cig_dw_ods_bitauto_website_d_pc_average' on line 33, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$cig_dw_ods_bitauto_website_d_pc_average')) # from line 33, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"cig_dw_ods_bitauto_website_d_pc_error",True) # u'$cig_dw_ods_bitauto_website_d_pc_error' on line 34, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$cig_dw_ods_bitauto_website_d_pc_error')) # from line 34, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"cig_dw_ods_bitauto_website_d_pc_explain",True) # u'$cig_dw_ods_bitauto_website_d_pc_explain' on line 35, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$cig_dw_ods_bitauto_website_d_pc_explain')) # from line 35, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"cig_dw_ods_bitauto_website_d_mobile",True) # u'$cig_dw_ods_bitauto_website_d_mobile' on line 38, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$cig_dw_ods_bitauto_website_d_mobile')) # from line 38, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"cig_dw_ods_bitauto_website_d_mobile_yesterday",True) # u'$cig_dw_ods_bitauto_website_d_mobile_yesterday' on line 39, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$cig_dw_ods_bitauto_website_d_mobile_yesterday')) # from line 39, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"cig_dw_ods_bitauto_website_d_mobile_average",True) # u'$cig_dw_ods_bitauto_website_d_mobile_average' on line 40, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$cig_dw_ods_bitauto_website_d_mobile_average')) # from line 40, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"cig_dw_ods_bitauto_website_d_mobile_error",True) # u'$cig_dw_ods_bitauto_website_d_mobile_error' on line 41, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$cig_dw_ods_bitauto_website_d_mobile_error')) # from line 41, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"cig_dw_ods_bitauto_website_d_mobile_explain",True) # u'$cig_dw_ods_bitauto_website_d_mobile_explain' on line 42, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$cig_dw_ods_bitauto_website_d_mobile_explain')) # from line 42, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_ad_meterial_info_day",True) # u'$auto2_tool_ad_meterial_info_day' on line 45, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_ad_meterial_info_day')) # from line 45, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_ad_meterial_info_day_yesterday",True) # u'$auto2_tool_ad_meterial_info_day_yesterday' on line 46, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_ad_meterial_info_day_yesterday')) # from line 46, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_ad_meterial_info_day_average",True) # u'$auto2_tool_ad_meterial_info_day_average' on line 47, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_ad_meterial_info_day_average')) # from line 47, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_ad_meterial_info_day_error",True) # u'$auto2_tool_ad_meterial_info_day_error' on line 48, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_ad_meterial_info_day_error')) # from line 48, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_ad_meterial_info_day_explain",True) # u'$auto2_tool_ad_meterial_info_day_explain' on line 49, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_ad_meterial_info_day_explain')) # from line 49, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_ad_place_info_day",True) # u'$auto2_tool_ad_place_info_day' on line 52, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_ad_place_info_day')) # from line 52, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_ad_place_info_day_yesterday",True) # u'$auto2_tool_ad_place_info_day_yesterday' on line 53, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_ad_place_info_day_yesterday')) # from line 53, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_ad_place_info_day_average",True) # u'$auto2_tool_ad_place_info_day_average' on line 54, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_ad_place_info_day_average')) # from line 54, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_ad_place_info_day_error",True) # u'$auto2_tool_ad_place_info_day_error' on line 55, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_ad_place_info_day_error')) # from line 55, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_ad_place_info_day_explain",True) # u'$auto2_tool_ad_place_info_day_explain' on line 56, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_ad_place_info_day_explain')) # from line 56, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_model_info_day",True) # u'$auto2_tool_model_info_day' on line 59, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_model_info_day')) # from line 59, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_model_info_day_yesterday",True) # u'$auto2_tool_model_info_day_yesterday' on line 60, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_model_info_day_yesterday')) # from line 60, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_model_info_day_average",True) # u'$auto2_tool_model_info_day_average' on line 61, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_model_info_day_average')) # from line 61, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_model_info_day_error",True) # u'$auto2_tool_model_info_day_error' on line 62, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_model_info_day_error')) # from line 62, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_model_info_day_explain",True) # u'$auto2_tool_model_info_day_explain' on line 63, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_model_info_day_explain')) # from line 63, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_price_day",True) # u'$auto2_tool_price_day' on line 66, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_price_day')) # from line 66, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_price_day_yesterday",True) # u'$auto2_tool_price_day_yesterday' on line 67, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_price_day_yesterday')) # from line 67, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_price_day_average",True) # u'$auto2_tool_price_day_average' on line 68, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_price_day_average')) # from line 68, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_price_day_error",True) # u'$auto2_tool_price_day_error' on line 69, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_price_day_error')) # from line 69, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_price_day_explain",True) # u'$auto2_tool_price_day_explain' on line 70, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_price_day_explain')) # from line 70, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_style_info_day",True) # u'$auto2_tool_style_info_day' on line 73, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_style_info_day')) # from line 73, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_style_info_day_yesterday",True) # u'$auto2_tool_style_info_day_yesterday' on line 74, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_style_info_day_yesterday')) # from line 74, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_style_info_day_average",True) # u'$auto2_tool_style_info_day_average' on line 75, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_style_info_day_average')) # from line 75, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_style_info_day_error",True) # u'$auto2_tool_style_info_day_error' on line 76, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_style_info_day_error')) # from line 76, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_style_info_day_explain",True) # u'$auto2_tool_style_info_day_explain' on line 77, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_style_info_day_explain')) # from line 77, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_shangpainum_month",True) # u'$auto2_tool_shangpainum_month' on line 80, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_shangpainum_month')) # from line 80, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_shangpainum_month_yesterday",True) # u'$auto2_tool_shangpainum_month_yesterday' on line 81, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_shangpainum_month_yesterday')) # from line 81, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_shangpainum_month_average",True) # u'$auto2_tool_shangpainum_month_average' on line 82, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_shangpainum_month_average')) # from line 82, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_shangpainum_month_error",True) # u'$auto2_tool_shangpainum_month_error' on line 83, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_shangpainum_month_error')) # from line 83, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"auto2_tool_shangpainum_month_explain",True) # u'$auto2_tool_shangpainum_month_explain' on line 84, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$auto2_tool_shangpainum_month_explain')) # from line 84, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"mobile_dw_stage_mobile_bjdq_d",True) # u'$mobile_dw_stage_mobile_bjdq_d' on line 87, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$mobile_dw_stage_mobile_bjdq_d')) # from line 87, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"mobile_dw_stage_mobile_bjdq_d_yesterday",True) # u'$mobile_dw_stage_mobile_bjdq_d_yesterday' on line 88, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$mobile_dw_stage_mobile_bjdq_d_yesterday')) # from line 88, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"mobile_dw_stage_mobile_bjdq_d_average",True) # u'$mobile_dw_stage_mobile_bjdq_d_average' on line 89, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$mobile_dw_stage_mobile_bjdq_d_average')) # from line 89, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"mobile_dw_stage_mobile_bjdq_d_error",True) # u'$mobile_dw_stage_mobile_bjdq_d_error' on line 90, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$mobile_dw_stage_mobile_bjdq_d_error')) # from line 90, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"mobile_dw_stage_mobile_bjdq_d_explain",True) # u'$mobile_dw_stage_mobile_bjdq_d_explain' on line 91, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$mobile_dw_stage_mobile_bjdq_d_explain')) # from line 91, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_leads",True) # u'$leads_cookie_leads' on line 94, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_leads')) # from line 94, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_leads_yesterday",True) # u'$leads_cookie_leads_yesterday' on line 95, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_leads_yesterday')) # from line 95, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_leads_average",True) # u'$leads_cookie_leads_average' on line 96, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_leads_average')) # from line 96, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_leads_error",True) # u'$leads_cookie_leads_error' on line 97, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_leads_error')) # from line 97, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_leads_explain",True) # u'$leads_cookie_leads_explain' on line 98, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_leads_explain')) # from line 98, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_leads_mobile",True) # u'$leads_cookie_leads_mobile' on line 101, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_leads_mobile')) # from line 101, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_leads_mobile_yesterday",True) # u'$leads_cookie_leads_mobile_yesterday' on line 102, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_leads_mobile_yesterday')) # from line 102, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_leads_mobile_average",True) # u'$leads_cookie_leads_mobile_average' on line 103, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_leads_mobile_average')) # from line 103, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_leads_mobile_error",True) # u'$leads_cookie_leads_mobile_error' on line 104, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_leads_mobile_error')) # from line 104, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_leads_mobile_explain",True) # u'$leads_cookie_leads_mobile_explain' on line 105, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_leads_mobile_explain')) # from line 105, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_cookie_map",True) # u'$leads_cookie_cookie_map' on line 108, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_cookie_map')) # from line 108, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_cookie_map_yesterday",True) # u'$leads_cookie_cookie_map_yesterday' on line 109, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_cookie_map_yesterday')) # from line 109, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_cookie_map_average",True) # u'$leads_cookie_cookie_map_average' on line 110, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_cookie_map_average')) # from line 110, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_cookie_map_error",True) # u'$leads_cookie_cookie_map_error' on line 111, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_cookie_map_error')) # from line 111, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"leads_cookie_cookie_map_explain",True) # u'$leads_cookie_cookie_map_explain' on line 112, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$leads_cookie_cookie_map_explain')) # from line 112, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"mobile_dw_stage_mobile_yiche_d",True) # u'$mobile_dw_stage_mobile_yiche_d' on line 115, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$mobile_dw_stage_mobile_yiche_d')) # from line 115, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"mobile_dw_stage_mobile_yiche_d_yesterday",True) # u'$mobile_dw_stage_mobile_yiche_d_yesterday' on line 116, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$mobile_dw_stage_mobile_yiche_d_yesterday')) # from line 116, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"mobile_dw_stage_mobile_yiche_d_average",True) # u'$mobile_dw_stage_mobile_yiche_d_average' on line 117, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$mobile_dw_stage_mobile_yiche_d_average')) # from line 117, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"mobile_dw_stage_mobile_yiche_d_error",True) # u'$mobile_dw_stage_mobile_yiche_d_error' on line 118, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$mobile_dw_stage_mobile_yiche_d_error')) # from line 118, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"mobile_dw_stage_mobile_yiche_d_explain",True) # u'$mobile_dw_stage_mobile_yiche_d_explain' on line 119, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$mobile_dw_stage_mobile_yiche_d_explain')) # from line 119, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"usercenter_dw_stage_tags_zamplus",True) # u'$usercenter_dw_stage_tags_zamplus' on line 122, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$usercenter_dw_stage_tags_zamplus')) # from line 122, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"usercenter_dw_stage_tags_zamplus_yesterday",True) # u'$usercenter_dw_stage_tags_zamplus_yesterday' on line 123, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$usercenter_dw_stage_tags_zamplus_yesterday')) # from line 123, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"usercenter_dw_stage_tags_zamplus_average",True) # u'$usercenter_dw_stage_tags_zamplus_average' on line 124, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$usercenter_dw_stage_tags_zamplus_average')) # from line 124, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"usercenter_dw_stage_tags_zamplus_error",True) # u'$usercenter_dw_stage_tags_zamplus_error' on line 125, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$usercenter_dw_stage_tags_zamplus_error')) # from line 125, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"usercenter_dw_stage_tags_zamplus_explain",True) # u'$usercenter_dw_stage_tags_zamplus_explain' on line 126, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$usercenter_dw_stage_tags_zamplus_explain')) # from line 126, col 21.
        write(u'''</td>\r
            </tr>\r
        </table>\r
\r
        <table border="3" align="center" width="100%" style="table-layout:fixed;word-break:break-all" >\r
            <caption>\r
                ''')
        _v = VFFSL(SL,"title_week",True) # u'$title_week' on line 132, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$title_week')) # from line 132, col 17.
        write(u'''\r
            </caption>\r
            <tr bgcolor="CornflowerBlue">\r
                <th style="word-break: keep-all">date</th>\r
                <th>''')
        _v = VFFSL(SL,"none_data_table",True) # u'$none_data_table' on line 136, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$none_data_table')) # from line 136, col 21.
        write(u'''</th>\r
                <th>''')
        _v = VFFSL(SL,"error_data_table",True) # u'$error_data_table' on line 137, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$error_data_table')) # from line 137, col 21.
        write(u'''</th>\r
            </tr>\r
            <tr>\r
                <td width="70" style="word-break: keep-all">''')
        _v = VFFSL(SL,"current_month_1date",True) # u'$current_month_1date' on line 140, col 61
        if _v is not None: write(_filter(_v, rawExpr=u'$current_month_1date')) # from line 140, col 61.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"none_table_1date",True) # u'$none_table_1date' on line 141, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$none_table_1date')) # from line 141, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"error_table_1date",True) # u'$error_table_1date' on line 142, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$error_table_1date')) # from line 142, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td style="word-break: keep-all">''')
        _v = VFFSL(SL,"current_month_2date",True) # u'$current_month_2date' on line 145, col 50
        if _v is not None: write(_filter(_v, rawExpr=u'$current_month_2date')) # from line 145, col 50.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"none_table_2date",True) # u'$none_table_2date' on line 146, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$none_table_2date')) # from line 146, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"error_table_2date",True) # u'$error_table_2date' on line 147, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$error_table_2date')) # from line 147, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td style="word-break: keep-all">''')
        _v = VFFSL(SL,"current_month_3date",True) # u'$current_month_3date' on line 150, col 50
        if _v is not None: write(_filter(_v, rawExpr=u'$current_month_3date')) # from line 150, col 50.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"none_table_3date",True) # u'$none_table_3date' on line 151, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$none_table_3date')) # from line 151, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"error_table_3date",True) # u'$error_table_3date' on line 152, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$error_table_3date')) # from line 152, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td style="word-break: keep-all">''')
        _v = VFFSL(SL,"current_month_4date",True) # u'$current_month_4date' on line 155, col 50
        if _v is not None: write(_filter(_v, rawExpr=u'$current_month_4date')) # from line 155, col 50.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"none_table_4date",True) # u'$none_table_4date' on line 156, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$none_table_4date')) # from line 156, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"error_table_4date",True) # u'$error_table_4date' on line 157, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$error_table_4date')) # from line 157, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td style="word-break: keep-all">''')
        _v = VFFSL(SL,"current_month_5date",True) # u'$current_month_5date' on line 160, col 50
        if _v is not None: write(_filter(_v, rawExpr=u'$current_month_5date')) # from line 160, col 50.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"none_table_5date",True) # u'$none_table_5date' on line 161, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$none_table_5date')) # from line 161, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"error_table_5date",True) # u'$error_table_5date' on line 162, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$error_table_5date')) # from line 162, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td style="word-break: keep-all">''')
        _v = VFFSL(SL,"current_month_6date",True) # u'$current_month_6date' on line 165, col 50
        if _v is not None: write(_filter(_v, rawExpr=u'$current_month_6date')) # from line 165, col 50.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"none_table_6date",True) # u'$none_table_6date' on line 166, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$none_table_6date')) # from line 166, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"error_table_6date",True) # u'$error_table_6date' on line 167, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$error_table_6date')) # from line 167, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td style="word-break: keep-all">''')
        _v = VFFSL(SL,"current_month_7date",True) # u'$current_month_7date' on line 170, col 50
        if _v is not None: write(_filter(_v, rawExpr=u'$current_month_7date')) # from line 170, col 50.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"none_table_7date",True) # u'$none_table_7date' on line 171, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$none_table_7date')) # from line 171, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"error_table_7date",True) # u'$error_table_7date' on line 172, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$error_table_7date')) # from line 172, col 21.
        write(u'''</td>\r
            </tr>\r
        </table>\r
        <table border="3" align="center" width="100%" style="table-layout:fixed;word-break:break-all" >\r
            <caption bgcolor="CornflowerBlue">\r
                ''')
        _v = VFFSL(SL,"title_month",True) # u'$title_month' on line 177, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$title_month')) # from line 177, col 17.
        write(u'''\r
            </caption>\r
            <tr bgcolor="CornflowerBlue">\r
                <th>1</th>\r
                <th>2</th>\r
                <th>3</th>\r
                <th>4</th>\r
                <th>5</th>\r
                <th>6</th>\r
                <th>7</th>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"month_date1",True) # u'$month_date1' on line 189, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date1')) # from line 189, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date2",True) # u'$month_date2' on line 190, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date2')) # from line 190, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date3",True) # u'$month_date3' on line 191, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date3')) # from line 191, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date4",True) # u'$month_date4' on line 192, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date4')) # from line 192, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date5",True) # u'$month_date5' on line 193, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date5')) # from line 193, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date6",True) # u'$month_date6' on line 194, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date6')) # from line 194, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date7",True) # u'$month_date7' on line 195, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date7')) # from line 195, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"month_date8",True) # u'$month_date8' on line 198, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date8')) # from line 198, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date9",True) # u'$month_date9' on line 199, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date9')) # from line 199, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date10",True) # u'$month_date10' on line 200, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date10')) # from line 200, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date11",True) # u'$month_date11' on line 201, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date11')) # from line 201, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date12",True) # u'$month_date12' on line 202, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date12')) # from line 202, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date13",True) # u'$month_date13' on line 203, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date13')) # from line 203, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date14",True) # u'$month_date14' on line 204, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date14')) # from line 204, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"month_date15",True) # u'$month_date15' on line 207, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date15')) # from line 207, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date16",True) # u'$month_date16' on line 208, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date16')) # from line 208, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date17",True) # u'$month_date17' on line 209, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date17')) # from line 209, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date18",True) # u'$month_date18' on line 210, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date18')) # from line 210, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date19",True) # u'$month_date19' on line 211, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date19')) # from line 211, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date20",True) # u'$month_date20' on line 212, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date20')) # from line 212, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date21",True) # u'$month_date21' on line 213, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date21')) # from line 213, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"month_date22",True) # u'$month_date22' on line 216, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date22')) # from line 216, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date23",True) # u'$month_date23' on line 217, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date23')) # from line 217, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date24",True) # u'$month_date24' on line 218, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date24')) # from line 218, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date25",True) # u'$month_date25' on line 219, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date25')) # from line 219, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date26",True) # u'$month_date26' on line 220, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date26')) # from line 220, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date27",True) # u'$month_date27' on line 221, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date27')) # from line 221, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date28",True) # u'$month_date28' on line 222, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date28')) # from line 222, col 21.
        write(u'''</td>\r
            </tr>\r
            <tr>\r
                <td>''')
        _v = VFFSL(SL,"month_date29",True) # u'$month_date29' on line 225, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date29')) # from line 225, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date30",True) # u'$month_date30' on line 226, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date30')) # from line 226, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date31",True) # u'$month_date31' on line 227, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date31')) # from line 227, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date32",True) # u'$month_date32' on line 228, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date32')) # from line 228, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date33",True) # u'$month_date33' on line 229, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date33')) # from line 229, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date34",True) # u'$month_date34' on line 230, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date34')) # from line 230, col 21.
        write(u'''</td>\r
                <td>''')
        _v = VFFSL(SL,"month_date35",True) # u'$month_date35' on line 231, col 21
        if _v is not None: write(_filter(_v, rawExpr=u'$month_date35')) # from line 231, col 21.
        write(u'''</td>\r
            </tr>\r
        </table>\r
    </body>\r
</html>\r
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_report_externel= 'respond'

## END CLASS DEFINITION

if not hasattr(report_externel, '_initCheetahAttributes'):
    templateAPIClass = getattr(report_externel, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(report_externel)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=report_externel()).run()


